### ISSUE TITLE
Missing Example - Testing Function from a Module

### ISSUE THREAD

**Issue by Yoshi325** [benjamin-hodgson/Contexts#11]
The documentation does not have an example of how to test a function in a module. There is an example for testing a method from a class. And examples showing standalone code (in the Triangulation section). But there are no examples on how to test functions that are part of a module.

I am having trouble testing just such a case (which is why I am requesting an example).

**Comment by benjamin-hodgson** [comment]
@Yoshi325 Testing a function which is part of a module is no different than testing anything else. Off the top of my head, here's an example:


```python
# spam.py
def ham(x, y):
    return x + y
```
```python
# test_spam.py
import spam

class WhenHammingTwoNumbers:
    def given_two_numbers(self):
        self.x = 3
        self.y = 5

    def when_i_ham_them(self):
        self.result = spam.ham(self.x, self.y)

    def it_should_calculate_the_sum(self):
        assert self.result == 8
```

I'd be happy to accept a pull request with a change to the docs. If not, I'll probably have time to write it up myself this weekend.

**Comment by Yoshi325** [comment]
Hrm, I must be doing something wrong. When I attempt to recreate that example with my code, I get the following AttributeError (edits in '<','>' for clarity):

E
----------------------------------------------------------------------
<TestClassName(spaces inserted based on casing)>
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/contexts/core.py", line 283, in run_context
      yield
    File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/contexts/core.py", line 195, in run
      self.run_action()
    File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/contexts/core.py", line 205, in run_action
      run_with_test_data(self.action, self.example)
    File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/contexts/core.py", line 240, in run_with_test_data
      func()
    File "<RepoRoot>/tests/test_<ModuleName>.py", line 20, in because_<...>
      self.result =  <ModuleName>.<ModuleMethod>(self.parameter_one, self.parameter_two)
  AttributeError: 'module' object has no attribute '_<TestClassName><ModuleMethod>'
----------------------------------------------------------------------

Do you have any suggestions for what I might be doing wrong?

**Comment by Yoshi325** [comment]
Here is my broken counter-example:

```python
# eggs/sunny/spam.py
def __treat(x, y):
    return x * y

def ham(x, y):
    return x + y
```

```python
# tests/test_spam.py
from eggs.sunny import spam

class WhenHammingTwoNumbers:
    def given_two_numbers(self):
        self.x = 3
        self.y = 5

    def when_i_ham_them(self):
        self.result = spam.ham(self.x, self.y)

    def it_should_calculate_the_sum(self):
        assert self.result == 8

class WhenTreatingTwoNumbers:
    def given_two_numbers(self):
        self.x = 3
        self.y = 5

    def when_i_treat_them(self):
        self.result = spam.__treat(self.x, self.y)

    def it_should_calculate_the_product(self):
        assert self.result == 15

if __name__ == '__main__':
    import contexts
    contexts.main()
```

```
$ python3 -m tests.test_spam
E.
----------------------------------------------------------------------
When treating two numbers
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/contexts/core.py", line 283, in run_context
      yield
    File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/contexts/core.py", line 195, in run
      self.run_action()
    File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/contexts/core.py", line 205, in run_action
      run_with_test_data(self.action, self.example)
    File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/contexts/core.py", line 240, in run_with_test_data
      func()
    File "contexts-test/tests/test_spam.py", line 21, in when_i_treat_them
      self.result = spam.__treat(self.x, self.y)
  AttributeError: 'module' object has no attribute '_WhenTreatingTwoNumbers__treat'
----------------------------------------------------------------------
FAILED!
2 contexts, 1 assertion: 0 failed, 1 error
(0.0 seconds)
```

**Comment by benjamin-hodgson** [comment]
I notice that you're having trouble with a function named `__treat`. I think you may be experiencing Python's weird [double-underscore-name-mangling behaviour](https://docs.python.org/3/tutorial/classes.html#private-variables).

To be clear, this is part of the Python language and nothing to do with any particular test framework. If you rename your function to, say, `_treat` (with a single underscore), does it work?

I generally avoid using double-underscores in names if I can help it. It's just too strange.

**Comment by Yoshi325** [comment]
Thank you for your patience. Your suggestion to reduce the name to a single underscore works perfectly. I started using the double underscore to indicate a private method in a class. And when writing a module I followed the same convention without thinking. I found a good breakdown about single versus double underscores for method names here: http://stackoverflow.com/a/1547160

**Comment by benjamin-hodgson** [comment]
Glad your issue is fixed! :smile:
