### ISSUE TITLE
Test Case Class Inheritance

### ISSUE THREAD

**Issue by Yoshi325** [benjamin-hodgson/Contexts#13]
If you have a test case class inherit from another class, contexts does not discover methods from the inherited class.

Is there a way to enforce this behavior that I have not located in the docs?

```python
class GroupChecker:
    def because_we_want_to_make_a_check_on_a_group(self, target, _):
        self.result = True
    def the_check_should_return(self, _, expected):
        assert self.result = True
````

**Comment by benjamin-hodgson** [comment]
I'm afraid I don't fully understand your question. Please could you post a complete code example and specify the behaviour you expected?

**Comment by Yoshi325** [comment]
Sorry, I had not realized that I posted before completing my example.

```python
class GroupChecker:
    def because_we_want_to_make_a_check_on_a_group(self, example, _):
        self.result = (True == example)
    def the_check_should_return(self, _, expected):
        assert self.result = True

class IndividualCheckerA(GroupChecker):
    @classmethod
    def examples_of_things_to_check_individually(self):
        yield True
        yield False
        yield True
        yield True

class IndividualCheckerB(GroupChecker):
    @classmethod
    def examples_of_things_to_check_individually(self):
        yield True
        yield False
        yield False
        yield False
```

I was hoping that doing this would provide two different sets of examples to the methods in the inherited class.

Does this make more sense?

**Comment by benjamin-hodgson** [comment]
What's wrong with putting your examples into a single test case?

```python
class GroupChecker:
    @classmethod
    def examples_of_things_to_check_individually(self):
        yield True
        yield False
        yield True
        yield True
        yield True
        yield False
        yield False
        yield False
    def because_we_want_to_make_a_check_on_a_group(self, example, _):
        self.result = (True == example)
    def the_check_should_return(self, _, expected):
        assert self.result = True
```

**Comment by Yoshi325** [comment]
The examples are sub-sets of a larger data set, and I need to identify them independently. In my use case there are actually 4 sub-sets. So I want the tests to identify which sub-set the data it is testing is under. The simplest way I have found to identify the sub-set is by using it in the name of the test class and the examples method.

**Comment by benjamin-hodgson** [comment]
Contexts doesn't run `when` or `then` methods from the base class - only `given` and `cleanup` methods. This is by design. I have seen plenty of tests which are hard to understand because the acting or asserting logic is hidden in a base class, so Contexts strongly encourages you to put your `when` and `then` methods in the test class itself. The idea is that the methods of a test case read like a sentence, which isn't possible when half the sentence is missing!

If you could give me a more concrete example (your actual code), I might be able to suggest an alternative design.

**Comment by Yoshi325** [comment]
Unfortunately the data sets are not mine to share, so I will have to ask permission.

Thank you for your explanation of how inheritance is handled. I think I understand why it is architected that way.

Is there any possibility of having multiple ```examples``` methods in one class? Or would that also go against the design of Contexts?

**Comment by benjamin-hodgson** [comment]
How about pulling collections out of your examples method?

```python
class GroupChecker:
    @classmethod
    def examples_of_groups(cls):
        yield [True, False, True, True]
        yield [True, False, False, False]
    def the_groups_should_all_be_true(self, example):
        assert all(example)
```

**Comment by Yoshi325** [comment]
I do not think that is a good fit for what I am working with.

Here is the code: https://github.com/Yoshi325/luhn_check/blob/python-3.0/tests/test_luhn.py

**Comment by benjamin-hodgson** [comment]
I'd slice it the other way. One test per method you're testing, but feeding in a variety of card numbers. If you want to print out the card type when the test fails, you can label the numbers (and then just ignore it in the test).

```python
valid_card_numbers = [
    ('amex', 378282246310005'),
    ('amex', 343434343434343'),
    # etc

    ('visa', '4111111111111111'),
    ('visa', '4007000000027'),
    # etc

    ('mastercard', '5105105105105100'),
    ('mastercard', '5111111111111118'),
    # etc

    ('discover', '6011111111111117'),
    ('discover', '6011000000000004')
    # etc
]

class WhenCheckingLuhnValidityOnValidCards:
    @classmethod
    def examples_of_valid_cards(cls):
        return valid_card_numbers
    def when_i_check_luhn_valid(self, card_type, card_number):
        self.result = luhn_check.is_luhn_valid(card_number)
    def it_should_be_valid(self, card_type, card_number):
        assert self.result

class WhenCheckingCardLengthOnValidCards:
    @classmethod
    def examples_of_valid_cards(cls):
        return valid_card_numbers
    def when_i_check_luhn_valid(self, card_type, card_number):
        self.result = luhn_check.is_card_length_valid(card_number)
    def it_should_be_valid(self, card_type, card_number):
        assert self.result

# etc
```
