### ISSUE TITLE
Inheritance of given

### ISSUE THREAD

**Issue by bobthemighty** [benjamin-hodgson/Contexts#14]
Is there a philosophical reason why you haven't implemented multiple given statements across an inheritance hierarchy?

I'm thinking of a situation like this:

```python
class with_fake_http:
    
     def given_an_http_client(self):
           httpretty.register_uri('myserver.com/*')
           httpretty.enable()

     def cleanup_httpretty(self):
           httpretty.reset()
           httpretty.cleanup()

     def fake_response(self, uri, body):
            ...

class when_fetching_a_widget(with_fake_http):
   
        def given_a_widget(self):
            self.fake_response('/widgets/1', {id: 'widget-1'})

        def because_we_fetch_the_widget(self):
            self.widget = requests.get('myserver.com/widgets/1')

        def it_should_have_the_correct_id(self):
           ...
```

Basically, I want to set up some infrastructural concerns in a parent class, so that the actual context can focus purely on the scenario under test. Obviously I can fix it by calling a method on my parent class in each context, but that feels like a smell.

**Comment by benjamin-hodgson** [comment]
Hay Bob,

That ought to be working right now, [per the tests](https://github.com/benjamin-hodgson/Contexts/blob/master/test/functional_tests/unit_tests.py#L231).

**Comment by bobthemighty** [comment]
O HAI Ben!

Funny, I thought that was working, which is why I was so surprised it
didn't.

I think maybe httpretty is messing with me, it doesn't like python 3.5 and
if there's an exception thrown anywhere, it all gets very metaphysical.

Thanks for the response, close the issue.
