### ISSUE TITLE
Support parallel tests

### ISSUE THREAD

**Issue by GordonSo** [benjamin-hodgson/Contexts#15]
Hi Ben, 

Is/ Will there be support for parallel tests in contexts?

Similar to xdist wth pytests where it would be great if the framework could discovers and create sub-processes to execute tests based on the number of nodes provided.

**Comment by benjamin-hodgson** [comment]
`pytest-xdist` is a plugin which is distributed separately from `pytest`. Contexts has a plugin architecture as well, though I've forgotten enough about it to be unsure whether I'd be able to support what you want as a plugin. Have you tried to implement it yourself?

**Comment by GordonSo** [comment]
Hey, hope you are good!

I'm looking to improve performance for our tests performance, and distributing them seems like a sensible route to go down. We have had some success with pytest-xdist but using unitests, we would, of course, like to keep all the goodness from context, so I am looking at implementing something similar if it's not too complicated.

I thought I'd raise the question here in case some great minds had the same thought already. ;)

**Comment by benjamin-hodgson** [comment]
One cheap (without writing any code) way of doing it would be to split up each batch of tests into a separate file and set up TeamCity jobs for each file. Then run the TC jobs in parallel. Main downside is you can't dynamically redistribute the load. Thoughts?

**Comment by GordonSo** [comment]
Seems like a pragmatic approach, I am a little wary that some test suits might be missed if we start listing test cases or grouping test files into folders. I will take a dive in the redistributed route and come back if I found anything. Thx!
