### ISSUE TITLE
Support for pycharm plugin

### ISSUE THREAD

**Issue by GordonSo** [benjamin-hodgson/Contexts#16]
Support for the ability to debug a contexts test via the pycharm debugger

**Comment by benjamin-hodgson** [comment]
Hi Gordon! Hope you're doing well and that Huddle hasn't gone bankrupt yet.

I don't know enough about PyCharm to tell you how much work this would involve. I suspect it ought to be possible to implement it as a separate project without substantial changes to the test runner itself. How much do you know about PyCharm's plugin support?
