### ISSUE TITLE
test matching is perhaps too liberal

### ISSUE THREAD

**Issue by bobthemighty** [benjamin-hodgson/Contexts#3]
"def when_we_set_an_itinerary" oughtn't to be ambiguous just because it happens to contain the substring "it".

Maybe we could attempt to tokenise the method names based on casing and work from there?

**Comment by benjamin-hodgson** [comment]
I agree. What's more, there's already some smartness about what constitutes a word and what doesn't, in the code which outputs names to the screen: https://github.com/benjamin-hodgson/Contexts/blob/master/src/contexts/plugins/reporting/__init__.py#L42
I have a few hours this afternoon, I'll see if I can get something working.

Hope things are going well at the new place! :sunglasses:

**Comment by benjamin-hodgson** [comment]
@bobthemighty Could you take the latest master for a spin and see if it solves your problem?

**Comment by bobthemighty** [comment]
Will do when I'm back in Python land.

Your little framework is so awesome that I'm essentially porting it to PHP:
https://github.com/bobthemighty/speciphy

Keep up the good work, man

On Sun, Mar 8, 2015 at 4:48 PM, Benjamin Hodgson <notifications@github.com>
wrote:

> @bobthemighty <https://github.com/bobthemighty> Could you take the latest
> master for a spin and see if it solves your problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benjamin-hodgson/Contexts/issues/3#issuecomment-77760542>
> .
>



-- 
Q. How many members of a demographic group does it take to perform a
specified task?

A. A finite number; one to perform the task, and the remainder to act in a
manner stereotypical of the group in question.

**Comment by benjamin-hodgson** [comment]
PHP? god help you

**Comment by benjamin-hodgson** [comment]
I'm releasing this bug fix as v0.10.2
